default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_development

test:
  <<: *default
  database: shop_test

  <<: *default
  database: shop_production
  username: <%= ENV["PROD_DB_USERNAME"] || "postgres" %>
  password: <%= ENV["PROD_DB_PASSWORD"] || "postgres" %>
  host: <%= ENV["PROD_DB_HOST"] || "localhost" %>
production:
  adapter: postgresql
  encoding: unicode
  database: shop_production
  username: <%= ENV["PROD_DB_USERNAME"] || "postgres" %>
  password: <%= ENV["PROD_DB_PASSWORD"] || "postgres" %>
  host: <%= ENV["PROD_DB_HOST"] || "localhost" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
