# Name of your application. Used to uniquely configure containers.
service: shop

# Name of the container image (Docker Hub: username/repo).
image: vivekjain1101/shop
ssh:
  user: ubuntu


# Deploy to these servers (your EC2 IP).
servers:
  web:
    - 13.218.40.131

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: false

  host: 13.218.40.131

# Docker Hub credentials
registry:
  server: registry.hub.docker.com
  username: vivekjain1101
  password:
    - DOCKER_REGISTRY_PASSWORD

# Inject ENV variables into containers
env:
  secret:
    - RAILS_MASTER_KEY
    - DOCKER_REGISTRY_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "shop_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
